### ISSUE TITLE
Adding @Alias annotation

### ISSUE THREAD

**Issue by wxipwastaken** [TriumphTeam/triumph-cmds#66]
Currently to add alias to a command you have to add it to `@Command` annotation: 
```
@Command(value = "name", alias = "alias")
// etc...
```
With this change you could add aliases with it's own annotation:
```
@Command("name")
@Alias("alias")
// etc...
```

**Comment by iGabyTM** [comment]
Why would you want two annotations instead of one?

**Comment by wxipwastaken** [comment]
> Why would you want two annotations instead of one? The end result is the same and looks cleaner imo.

I don't like how it looks when in one annotation? It looks cleaner in two annotations

**Comment by iGabyTM** [comment]
It will stay all in one annotation, it is much easier to work with one annotation than multiple that do the same job.

**Comment by ipsk** [comment]
Yeah, it'll stay as 1 annotation, you can always pass it to the constructor if you don't like how it looks.
