### ISSUE TITLE
Allow parsing of string into Arguments object

### ISSUE THREAD

**Issue by viveleroi** [TriumphTeam/triumph-cmds#68]
I need a way to turn a string of commands/arguments/etc into an `Arguments` object.

Our reasoning is because the same NamedArguments we use in-game can be set in config files as defaults or easily re-usable search params (and params to use for purging data). Because the user is not entering these values as a command, I need some way to parse them.

Maybe something like `Arguments arguments = namedArguments.parse('prism lookup p:viveleroi since:3d')`

**Comment by c99SRS** [comment]
HI @viveleroi can you assign this one to me under hacktoberfest22 tag?

**Comment by viveleroi** [comment]
I don't have access to that, sorry.

**Comment by BlitzOffline** [comment]
> HI @viveleroi can you assign this one to me under hacktoberfest22 tag?

The repository already has the `hacktoberfest` tag so if you make the PR and it gets accepted until October 31st it will count.
