### ISSUE TITLE
Arguments need validation

### ISSUE THREAD

**Issue by viveleroi** [TriumphTeam/triumph-cmds#70]
1. Arguments should be validated by type. If I use `Argument.forInt().name("r").build()`, `r:test` should return an error to the user.
2. It would be nice to provide a regex/custom validator method. I need to parse a coordinate to x,y,z format.
3. I would also want the ability to customize the message returned to the user. I use localization so it would be nice to have an error interceptor or something.

**Comment by LichtHund** [comment]
Fixed on #84.
