### ISSUE TITLE
Inconsistent nullability annotation targets

### ISSUE THREAD

**Issue by Sparky983** [TriumphTeam/triumph-cmds#79]
Currently all jetbrains nullability annotations are targeting different elements. 

For example here:

[BukkitAsyncExecutionProvider.java](https://github.com/TriumphTeam/triumph-cmds/blob/master/minecraft/bukkit/src/main/java/dev/triumphteam/cmd/bukkit/BukkitAsyncExecutionProvider.java)
```java
public final class BukkitAsyncExecutionProvider implements ExecutionProvider {

    private final Plugin plugin;

    public BukkitAsyncExecutionProvider(@NotNull final Plugin plugin) {
        this.plugin = plugin;
    }

    public void execute(final @NotNull Runnable command) {
        Bukkit.getScheduler().runTaskAsynchronously(plugin, command);
    }
}
````

The constructor parameter `@NotNull` annotation comes before the `final` keyword so it targets the parameter, but in the execute parameter the `@NotNull` annotation comes after the `final` so it targets the `Runnable` type. This is the inconsistency I am looking to fix.

I believe that targeting we should target the type because it was intended to replace annotating methods, parameters, fields, etc with the actual type itself. The [JEP](https://openjdk.org/jeps/104) also states that the change was made in order for developers to "refine Java's built-in type system" which is what nullability annotations do.

I'm happy to make the PR, all I need is the green flag to do so.

**Comment by LichtHund** [comment]
Sounds good to me. At first it was mostly preference but I know the latter is the correct way, but it was already too late and the project got big so I couldn't be bothered to change it and stuck with how it was.
If you want to go through the trouble of doing it then sure, you're more than welcome to do so.
