### ISSUE TITLE
Optionals in arguments

### ISSUE THREAD

**Issue by neziw** [TriumphTeam/triumph-cmds#88]
It would be nice if we can use `Optional<?>` in arguments. Optionals allow us to easily manage the presence or absence of arguments in a more organized and efficient manner, without the need for complex null check statements. This can lead to faster development and make working with arguments much simple. I hope it will be added in the recode :)

**Comment by Creper132** [comment]
yes yes

**Comment by xMrAfonso** [comment]
I just got confused ngl, isn't the Optional annoation already a thing?

**Comment by neziw** [comment]
> I just got confused ngl, isn't the Optional annoation already a thing?

I don't mean optional annotation, I just mean Optional class from java

**Comment by zrdzn** [comment]
You shouldn't use Optionals in parameters, even IntelliJ throws warnings about that.

**Comment by LichtHund** [comment]
I had considered this in the past, however there are a few problems.
First using Optionals as parameters are against Java's convention, hence why Intellij will warn you against it.
Second I am assuming you're using the older version of the library in which all arguments are nullable, this is no longer the case as of 2.0.0-SNAPSHOT+.
And a single argument (the last argument), except on platforms like Discord ones.
The library does use Optionals when using named arguments (feature of 2.0.0).
